#!/usr/bin/with-contenv bash

#s6-svwait -U /var/run/service/rclone

if [[ -n "${COMMAND_CRON:-}" ]] && [[ -n "${COMMAND_CRON_COMMAND:-}" ]] ; then
    echo "*** scheduling job: $COMMAND_CRON_COMMAND"
    go-cron "$COMMAND_CRON" "$COMMAND_CRON_COMMAND" &
    sleep 2
fi

exec wait