#!/usr/bin/with-contenv bash

#s6-svwait -U /var/run/service/rclone

if [[ -n "${rclone_cron:-}" ]] && [[ -n "${rclone_cron_command:-}" ]] ; then
    echo "*** scheduling cron job: ${rclone_cron} - ${rclone_cron_command}"
    go-cron "$rclone_cron" "$rclone_cron_command" &
    sleep 2
fi

exec wait