#!/usr/bin/with-contenv bash
. /usr/local/bin/variables


if [ -z "$pd_mountpoint" ]; then
    echo "plexdrive not configured for use. plexdrive not started as a service"
    sleep ${sleep_delay}
else
    IFS=" " read -r -a pd_user_opts <<< "$PLEXDRIVE_MOUNT_USER_OPTS"

    mount_command="plexdrive mount ${pd_mountpoint} $(echo $pd_basic_opts) ${pd_user_opts[@]}"
    echo "*** mounting => $mount_command"
    exec s6-notifyoncheck -d -n 0 -s 3000 \
        s6-setuidgid abc $mount_command
fi