#!/usr/bin/with-contenv bash
. /usr/local/bin/variables


# plexdrive healthchecks
if ! [ -z "$pd_mountpoint" ]; then
    echo "*** checking plexdrive config"
    if ! [ -z "$plexdrive_rclone_remote" ]; then
        echo "Overwriting json config files in ${plexdrive_config_folder} using rclone remote: $plexdrive_rclone_remote"
        . /usr/local/bin/plexdrive_setup_from_rclone.script
        # Reload variables to ensure $plexdrive_teamdrive_id is populated and added to pd_basic_opts
        . /usr/local/bin/variables
    fi

    while [ ! -f "${plexdrive_config_folder}/config.json" ] || [ ! -f "${plexdrive_config_folder}/token.json" ]; do
        echo "Waiting for config files in ${plexdrive_config_folder}. Retrying in 30s ..."
        echo "RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup"
        echo "or set the name of a rclone remote to copy config from to environment variable: PLEXDRIVE_REMOTE"
        sleep 30
    done

    echo "*** checking plexdrive mountpoint: ${pd_mountpoint}"
    while findmnt "${pd_mountpoint}" | grep -q fuse; do
        echo "ERROR: mountpoint (${pd_mountpoint}) already mounted"
        fusermount -uz "${pd_mountpoint}"
        echo "Retrying in 15s ..."
        sleep 15
    done

    # permissions
    chown -R abc:abc \
        "${plexdrive_config_folder}" "${pd_mountpoint}" /cache
    chown abc:abc /local

    # display version
    echo "*** plexdrive $(plexdrive --version) ready!"
fi
