#!/usr/bin/with-contenv bash
. /usr/local/bin/variables


# plexdrive healthchecks
if ! [ -z "$pd_mountpoint" ]; then
    echo "*** checking config"
    if ! [ -z "$plexdrive_rclone_remote" ]; do
        echo "Overwriting json config files in /config using rclone remote: $plexdrive_rclone_remote"
    done

    while [ ! -f "/config/config.json" ] || [ ! -f "/config/token.json" ]; do
        echo "Waiting for config files in /config. Retrying in 30s ..."
        echo "RUN: docker exec -it <CONTAINER_NAME> plexdrive_setup"
        echo "or set the name of a rclone remote to copy config from to environment variable: PLEXDRIVE_REMOTE"
        sleep 30
    done

    echo "*** checking mountpoint: ${pd_mountpoint}"
    while findmnt "${pd_mountpoint}" | grep -q fuse; do
        echo "ERROR: mountpoint (${pd_mountpoint}) already mounted"
        fusermount -uz "${pd_mountpoint}"
        echo "Retrying in 15s ..."
        sleep 15
    done

    # permissions
    chown -R abc:abc \
        /config "${pd_mountpoint}" /cache
    chown abc:abc /local

    # display version
    echo "*** plexdrive $(plexdrive --version) ready!"
fi
